name: trstechnical
favicon: null
layout_spectrum: 0.5569018318783492
typography_spectrum: 0.9308915776200593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4967580728698522
  lightness: 0.7018308364786208
  saturation: 0.9325071009807289
  rhythmicContrast: 0.5107647038530558
purpose: []
